struct tree_variables
{
	// setup tree inputs
	// gen level info
	float gr_radion_p4_pt, gr_radion_p4_eta, gr_radion_p4_phi, gr_radion_p4_mass;
	float gr_hgg_p4_pt, gr_hgg_p4_eta, gr_hgg_p4_phi, gr_hgg_p4_mass;
	float gr_hbb_p4_pt, gr_hbb_p4_eta, gr_hbb_p4_phi, gr_hbb_p4_mass;
	float gr_hjj_p4_pt, gr_hjj_p4_eta, gr_hjj_p4_phi, gr_hjj_p4_mass;
	float gr_g1_p4_pt, gr_g1_p4_eta, gr_g1_p4_phi, gr_g1_p4_mass;
	float gr_g2_p4_pt, gr_g2_p4_eta, gr_g2_p4_phi, gr_g2_p4_mass;
	float gr_b1_p4_pt, gr_b1_p4_eta, gr_b1_p4_phi, gr_b1_p4_mass;
	float gr_b2_p4_pt, gr_b2_p4_eta, gr_b2_p4_phi, gr_b2_p4_mass;
	float gr_j1_p4_pt, gr_j1_p4_eta, gr_j1_p4_phi, gr_j1_p4_mass;
	float gr_j2_p4_pt, gr_j2_p4_eta, gr_j2_p4_phi, gr_j2_p4_mass;
// event variables
	float met_corr_pfmet, met_corr_phi_pfmet, met_corr_eta_pfmet, met_corr_e_pfmet;
	float pu_n, nvtx, rho;
	float weight, evweight, pu_weight;
	float run, lumis, event;
	float ph1_SCEta, ph2_SCEta;
	float ev_weight, ev_evweight, ev_pu_weight;
// object variables
	float ph1_eta, ph2_eta, ph1_pt, ph2_pt, PhotonsMass, ph1_phi, ph2_phi, ph1_e, ph2_e, ph1_r9, ph2_r9, ph1_sieie, ph2_sieie, ph1_hoe, ph2_hoe;
	float ph1_pfchargedisogood03, ph1_ecaliso, ph1_pfchargedisobad04, ph1_ecalisobad, ph1_badvtx_Et, ph1_isconv;
	float ph2_pfchargedisogood03, ph2_ecaliso, ph2_pfchargedisobad04, ph2_ecalisobad, ph2_badvtx_Et, ph2_isconv;
	int ph1_ciclevel, ph2_ciclevel, ph1_isEB, ph2_isEB;

	float j1_e, j1_pt, j1_phi, j1_eta, j1_beta, j1_betaStar, j1_betaStarClassic, j1_dR2Mean, j1_csvBtag, j1_csvMvaBtag, j1_jetProbBtag, j1_tcheBtag, j1_secVtxPt, j1_secVtx3dL, j1_emfrac, j1_hadfrac, j1_axis1, j1_axis2, j1_pull, j1_radionMatched, j1_btagSF;
	int j1_ntk, j1_nNeutrals, j1_nCharged;

	float j2_e, j2_pt, j2_phi, j2_eta, j2_beta, j2_betaStar, j2_betaStarClassic, j2_dR2Mean, j2_csvBtag, j2_csvMvaBtag, j2_jetProbBtag, j2_tcheBtag, j2_secVtxPt, j2_secVtx3dL, j2_emfrac, j2_hadfrac, j2_axis1, j2_axis2, j2_pull, j2_radionMatched, j2_btagSF;
	int j2_ntk, j2_nNeutrals, j2_nCharged;

	float j3_e, j3_pt, j3_phi, j3_eta, j3_beta, j3_betaStar, j3_betaStarClassic, j3_dR2Mean, j3_csvBtag, j3_csvMvaBtag, j3_jetProbBtag, j3_tcheBtag, j3_secVtxPt, j3_secVtx3dL, j3_emfrac, j3_hadfrac, j3_axis1, j3_axis2, j3_pull, j3_radionMatched, j3_btagSF;
	int j3_ntk, j3_nNeutrals, j3_nCharged;

	float j4_e, j4_pt, j4_phi, j4_eta, j4_beta, j4_betaStar, j4_betaStarClassic, j4_dR2Mean, j4_csvBtag, j4_csvMvaBtag, j4_jetProbBtag, j4_tcheBtag, j4_secVtxPt, j4_secVtx3dL, j4_emfrac, j4_hadfrac, j4_axis1, j4_axis2, j4_pull, j4_radionMatched, j4_btagSF;
	int j4_ntk, j4_nNeutrals, j4_nCharged;

	float jet_e, jet_pt, jet_phi, jet_eta;
	float jet_betaStarClassic, jet_dR2Mean, jet_csvBtag;
	float jet_secVtxPt, jet_secVtx3dL, jet_emfrac, jet_hadfrac, jet_btagSF;
	int jet_nNeutrals, jet_nCharged, jet_nConstituents;
	float jet_nConstituents_;
	float jet_dPhiMet_fabs;
	float jet_dPhiMet, jet_radionMatched, jet_regPt, jet_regkinPt;

// setup tree outputs
	float vtx_z;
	float pho1_pt, pho1_e, pho1_phi, pho1_eta, pho1_mass, pho1_r9, pho1_sieie, pho1_hoe;
	float pho2_pt, pho2_e, pho2_phi, pho2_eta, pho2_mass, pho2_r9, pho2_sieie, pho2_hoe;
	int pho1_isEB, pho2_isEB;
	float pho1_pfchargedisogood03, pho1_ecaliso, pho1_pfchargedisobad04, pho1_ecalisobad, pho1_badvtx_Et, pho1_PFisoA, pho1_PFisoB, pho1_PFisoC, pho1_isconv;
	float pho2_pfchargedisogood03, pho2_ecaliso, pho2_pfchargedisobad04, pho2_ecalisobad, pho2_badvtx_Et, pho2_PFisoA, pho2_PFisoB, pho2_PFisoC, pho2_isconv;
	float jet1_pt, jet1_e, jet1_phi, jet1_eta, jet1_mass, jet1_csvBtag, jet1_btagSF, jet1_betaStarClassic, jet1_dR2Mean;
	float jet2_pt, jet2_e, jet2_phi, jet2_eta, jet2_mass, jet2_csvBtag, jet2_btagSF, jet2_betaStarClassic, jet2_dR2Mean;
	float regjet1_emfrac, regjet1_hadfrac, regjet1_secVtxPt, regjet1_secVtx3dL, regjet1_dPhiMet;
	int regjet1_nConstituents;
	float regjet2_emfrac, regjet2_hadfrac, regjet2_secVtxPt, regjet2_secVtx3dL, regjet2_dPhiMet;
	int regjet2_nConstituents;
	float regjet1_pt, regjet1_e, regjet1_phi, regjet1_eta, regjet1_mass, regjet1_csvBtag, regjet1_btagSF, regjet1_betaStarClassic, regjet1_dR2Mean;
	float regjet2_pt, regjet2_e, regjet2_phi, regjet2_eta, regjet2_mass, regjet2_csvBtag, regjet2_btagSF, regjet2_betaStarClassic, regjet2_dR2Mean;
	float regkinjet1_pt, regkinjet1_e, regkinjet1_phi, regkinjet1_eta, regkinjet1_mass, regkinjet1_csvBtag, regkinjet1_btagSF, regkinjet1_betaStarClassic, regkinjet1_dR2Mean;
	float regkinjet2_pt, regkinjet2_e, regkinjet2_phi, regkinjet2_eta, regkinjet2_mass, regkinjet2_csvBtag, regkinjet2_btagSF, regkinjet2_betaStarClassic, regkinjet2_dR2Mean;
	float kinjet1_pt, kinjet1_e, kinjet1_phi, kinjet1_eta, kinjet1_mass, kinjet1_csvBtag, kinjet1_btagSF, kinjet1_betaStarClassic, kinjet1_dR2Mean;
	float kinjet2_pt, kinjet2_e, kinjet2_phi, kinjet2_eta, kinjet2_mass, kinjet2_csvBtag, kinjet2_btagSF, kinjet2_betaStarClassic, kinjet2_dR2Mean;
	float jj_pt, jj_e, jj_phi, jj_eta, jj_mass, jj_DR, jj_btagSF;
	float regjj_pt, regjj_e, regjj_phi, regjj_eta, regjj_mass, regjj_btagSF;
	float regkinjj_pt, regkinjj_e, regkinjj_phi, regkinjj_eta, regkinjj_mass, regkinjj_btagSF;
	float kinjj_pt, kinjj_e, kinjj_phi, kinjj_eta, kinjj_mass, kinjj_btagSF;
	float gg_pt, gg_e, gg_phi, gg_eta, gg_mass;
	float ggjj_pt, ggjj_e, ggjj_phi, ggjj_eta, ggjj_mass, regjj_DR, regkinjj_DR, kinjj_DR;
	float regggjj_pt, regggjj_e, regggjj_phi, regggjj_eta, regggjj_mass;
	float regkinggjj_pt, regkinggjj_e, regkinggjj_phi, regkinggjj_eta, regkinggjj_mass;
	float kinggjj_pt, kinggjj_e, kinggjj_phi, kinggjj_eta, kinggjj_mass;
	int selection_cut_level;
	int category;
	float costhetastar, regcosthetastar, regkincosthetastar, kincosthetastar;
	float minDRgj, minDRgregj, minDRgregkinj, minDRgkinj;
	float HT_gg;

	int njets_passing_kLooseID;
	int njets_passing_kLooseID_and_CSVM;
	int njets_kLooseID, njets_kRadionID;
	int njets_kLooseID_and_CSVM, njets_kRadionID_and_CSVM;
};

void initialize_variables(tree_variables *t)
{
	t->gr_radion_p4_pt = t->gr_radion_p4_eta = t->gr_radion_p4_phi = t->gr_radion_p4_mass = 0.;
	t->gr_hgg_p4_pt = t->gr_hgg_p4_eta = t->gr_hgg_p4_phi = t->gr_hgg_p4_mass = 0.;
	t->gr_hbb_p4_pt = t->gr_hbb_p4_eta = t->gr_hbb_p4_phi = t->gr_hbb_p4_mass = 0.;
	t->gr_hjj_p4_pt = t->gr_hjj_p4_eta = t->gr_hjj_p4_phi = t->gr_hjj_p4_mass = 0.;
	t->gr_g1_p4_pt = t->gr_g1_p4_eta = t->gr_g1_p4_phi = t->gr_g1_p4_mass = 0.;
	t->gr_g2_p4_pt = t->gr_g2_p4_eta = t->gr_g2_p4_phi = t->gr_g2_p4_mass = 0.;
	t->gr_b1_p4_pt = t->gr_b1_p4_eta = t->gr_b1_p4_phi = t->gr_b1_p4_mass = 0.;
	t->gr_b2_p4_pt = t->gr_b2_p4_eta = t->gr_b2_p4_phi = t->gr_b2_p4_mass = 0.;
	t->gr_j1_p4_pt = t->gr_j1_p4_eta = t->gr_j1_p4_phi = t->gr_j1_p4_mass = 0.;
	t->gr_j2_p4_pt = t->gr_j2_p4_eta = t->gr_j2_p4_phi = t->gr_j2_p4_mass = 0.;
	t->selection_cut_level = 0;
	t->category = 0;

	return;
}

void setup_intree(TTree* intree, tree_variables *t, int type)
{
	intree->SetBranchAddress("njets_passing_kLooseID", &t->njets_passing_kLooseID);
	intree->SetBranchAddress("njets_passing_kLooseID_and_CSVM", &t->njets_passing_kLooseID_and_CSVM);
	intree->SetBranchAddress("ph1_eta", &t->ph1_eta);
	intree->SetBranchAddress("ph2_eta", &t->ph2_eta);
	intree->SetBranchAddress("ph1_pt", &t->ph1_pt);
	intree->SetBranchAddress("ph2_pt", &t->ph2_pt);
	intree->SetBranchAddress("ph1_phi", &t->ph1_phi);
	intree->SetBranchAddress("ph2_phi", &t->ph2_phi);
	intree->SetBranchAddress("ph1_e", &t->ph1_e);
	intree->SetBranchAddress("ph2_e", &t->ph2_e);
	intree->SetBranchAddress("ph1_r9", &t->ph1_r9);
	intree->SetBranchAddress("ph2_r9", &t->ph2_r9);
	intree->SetBranchAddress("ph1_sieie", &t->ph1_sieie);
	intree->SetBranchAddress("ph2_sieie", &t->ph2_sieie);
	intree->SetBranchAddress("ph1_hoe", &t->ph1_hoe);
	intree->SetBranchAddress("ph2_hoe", &t->ph2_hoe);
	intree->SetBranchAddress("ph1_isEB", &t->ph1_isEB);
	intree->SetBranchAddress("ph2_isEB", &t->ph2_isEB);
	intree->SetBranchAddress("ph1_pfchargedisogood03", &t->ph1_pfchargedisogood03);
	intree->SetBranchAddress("ph2_pfchargedisogood03", &t->ph2_pfchargedisogood03);
	intree->SetBranchAddress("ph1_ecaliso", &t->ph1_ecaliso);
	intree->SetBranchAddress("ph2_ecaliso", &t->ph2_ecaliso);
	intree->SetBranchAddress("ph1_pfchargedisobad04", &t->ph1_pfchargedisobad04);
	intree->SetBranchAddress("ph2_pfchargedisobad04", &t->ph2_pfchargedisobad04);
	intree->SetBranchAddress("ph1_ecalisobad", &t->ph1_ecalisobad);
	intree->SetBranchAddress("ph2_ecalisobad", &t->ph2_ecalisobad);
	intree->SetBranchAddress("ph1_badvtx_Et", &t->ph1_badvtx_Et);
	intree->SetBranchAddress("ph2_badvtx_Et", &t->ph2_badvtx_Et);
	intree->SetBranchAddress("ph1_isconv", &t->ph1_isconv);
	intree->SetBranchAddress("ph2_isconv", &t->ph2_isconv);
	intree->SetBranchAddress("PhotonsMass", &t->PhotonsMass);
	intree->SetBranchAddress("ph1_ciclevel", &t->ph1_ciclevel);
	intree->SetBranchAddress("ph2_ciclevel", &t->ph2_ciclevel);
	intree->SetBranchAddress("met_corr_pfmet", &t->met_corr_pfmet);
	intree->SetBranchAddress("met_corr_phi_pfmet", &t->met_corr_phi_pfmet);
	intree->SetBranchAddress("met_corr_eta_pfmet", &t->met_corr_eta_pfmet);
	intree->SetBranchAddress("met_corr_e_pfmet", &t->met_corr_e_pfmet);
	intree->SetBranchAddress("pu_n", &t->pu_n);
	intree->SetBranchAddress("nvtx", &t->nvtx);
	intree->SetBranchAddress("rho", &t->rho);
	intree->SetBranchAddress("run", &t->run);
	intree->SetBranchAddress("lumis", &t->lumis);
	intree->SetBranchAddress("event", &t->event);
	intree->SetBranchAddress("ph1_SCEta", &t->ph1_SCEta);
	intree->SetBranchAddress("ph2_SCEta", &t->ph2_SCEta);
	intree->SetBranchAddress("weight", &t->ev_weight);
	intree->SetBranchAddress("evweight", &t->ev_evweight);
	intree->SetBranchAddress("pu_weight", &t->ev_pu_weight);
	intree->SetBranchAddress("vtx_z", &t->vtx_z);

	if( type < -250 )
	{
		intree->SetBranchAddress("gr_radion_p4_pt", &t->gr_radion_p4_pt);
		intree->SetBranchAddress("gr_radion_p4_eta", &t->gr_radion_p4_eta);
		intree->SetBranchAddress("gr_radion_p4_phi", &t->gr_radion_p4_phi);
		intree->SetBranchAddress("gr_radion_p4_mass", &t->gr_radion_p4_mass);
		intree->SetBranchAddress("gr_hgg_p4_pt", &t->gr_hgg_p4_pt);
		intree->SetBranchAddress("gr_hgg_p4_eta", &t->gr_hgg_p4_eta);
		intree->SetBranchAddress("gr_hgg_p4_phi", &t->gr_hgg_p4_phi);
		intree->SetBranchAddress("gr_hgg_p4_mass", &t->gr_hgg_p4_mass);
		intree->SetBranchAddress("gr_hbb_p4_pt", &t->gr_hbb_p4_pt);
		intree->SetBranchAddress("gr_hbb_p4_eta", &t->gr_hbb_p4_eta);
		intree->SetBranchAddress("gr_hbb_p4_phi", &t->gr_hbb_p4_phi);
		intree->SetBranchAddress("gr_hbb_p4_mass", &t->gr_hbb_p4_mass);
		intree->SetBranchAddress("gr_g1_p4_pt", &t->gr_g1_p4_pt);
		intree->SetBranchAddress("gr_g1_p4_eta", &t->gr_g1_p4_eta);
		intree->SetBranchAddress("gr_g1_p4_phi", &t->gr_g1_p4_phi);
		intree->SetBranchAddress("gr_g1_p4_mass", &t->gr_g1_p4_mass);
		intree->SetBranchAddress("gr_g2_p4_pt", &t->gr_g2_p4_pt);
		intree->SetBranchAddress("gr_g2_p4_eta", &t->gr_g2_p4_eta);
		intree->SetBranchAddress("gr_g2_p4_phi", &t->gr_g2_p4_phi);
		intree->SetBranchAddress("gr_g2_p4_mass", &t->gr_g2_p4_mass);
		intree->SetBranchAddress("gr_b1_p4_pt", &t->gr_b1_p4_pt);
		intree->SetBranchAddress("gr_b1_p4_eta", &t->gr_b1_p4_eta);
		intree->SetBranchAddress("gr_b1_p4_phi", &t->gr_b1_p4_phi);
		intree->SetBranchAddress("gr_b1_p4_mass", &t->gr_b1_p4_mass);
		intree->SetBranchAddress("gr_b2_p4_pt", &t->gr_b2_p4_pt);
		intree->SetBranchAddress("gr_b2_p4_eta", &t->gr_b2_p4_eta);
		intree->SetBranchAddress("gr_b2_p4_phi", &t->gr_b2_p4_phi);
		intree->SetBranchAddress("gr_b2_p4_mass", &t->gr_b2_p4_mass);
		intree->SetBranchAddress("gr_j1_p4_pt", &t->gr_j1_p4_pt);
		intree->SetBranchAddress("gr_j1_p4_eta", &t->gr_j1_p4_eta);
		intree->SetBranchAddress("gr_j1_p4_phi", &t->gr_j1_p4_phi);
		intree->SetBranchAddress("gr_j1_p4_mass", &t->gr_j1_p4_mass);
		intree->SetBranchAddress("gr_j2_p4_pt", &t->gr_j2_p4_pt);
		intree->SetBranchAddress("gr_j2_p4_eta", &t->gr_j2_p4_eta);
		intree->SetBranchAddress("gr_j2_p4_phi", &t->gr_j2_p4_phi);
		intree->SetBranchAddress("gr_j2_p4_mass", &t->gr_j2_p4_mass);
	}
	intree->SetBranchAddress("j1_e", &t->j1_e);
	intree->SetBranchAddress("j1_pt", &t->j1_pt);
	intree->SetBranchAddress("j1_phi", &t->j1_phi);
	intree->SetBranchAddress("j1_eta", &t->j1_eta);
	intree->SetBranchAddress("j1_beta", &t->j1_beta);
	intree->SetBranchAddress("j1_betaStar", &t->j1_betaStar);
	intree->SetBranchAddress("j1_betaStarClassic", &t->j1_betaStarClassic);
	intree->SetBranchAddress("j1_dR2Mean", &t->j1_dR2Mean);
	intree->SetBranchAddress("j1_csvBtag", &t->j1_csvBtag);
	intree->SetBranchAddress("j1_csvMvaBtag", &t->j1_csvMvaBtag);
	intree->SetBranchAddress("j1_jetProbBtag", &t->j1_jetProbBtag);
	intree->SetBranchAddress("j1_tcheBtag", &t->j1_tcheBtag);
	intree->SetBranchAddress("j1_radionMatched", &t->j1_radionMatched);
	intree->SetBranchAddress("j1_secVtxPt", &t->j1_secVtxPt);
	intree->SetBranchAddress("j1_secVtx3dL", &t->j1_secVtx3dL);
	intree->SetBranchAddress("j1_emfrac", &t->j1_emfrac);
	intree->SetBranchAddress("j1_hadfrac", &t->j1_hadfrac);
	intree->SetBranchAddress("j1_btagSF", &t->j1_btagSF);
	intree->SetBranchAddress("j1_ntk", &t->j1_ntk);
	intree->SetBranchAddress("j1_nNeutrals", &t->j1_nNeutrals);
	intree->SetBranchAddress("j1_nCharged", &t->j1_nCharged);
	intree->SetBranchAddress("j1_axis1", &t->j1_axis1);
	intree->SetBranchAddress("j1_axis2", &t->j1_axis2);
	intree->SetBranchAddress("j1_pull", &t->j1_pull);

	intree->SetBranchAddress("j2_e", &t->j2_e);
	intree->SetBranchAddress("j2_pt", &t->j2_pt);
	intree->SetBranchAddress("j2_phi", &t->j2_phi);
	intree->SetBranchAddress("j2_eta", &t->j2_eta);
	intree->SetBranchAddress("j2_beta", &t->j2_beta);
	intree->SetBranchAddress("j2_betaStar", &t->j2_betaStar);
	intree->SetBranchAddress("j2_betaStarClassic", &t->j2_betaStarClassic);
	intree->SetBranchAddress("j2_dR2Mean", &t->j2_dR2Mean);
	intree->SetBranchAddress("j2_csvBtag", &t->j2_csvBtag);
	intree->SetBranchAddress("j2_csvMvaBtag", &t->j2_csvMvaBtag);
	intree->SetBranchAddress("j2_jetProbBtag", &t->j2_jetProbBtag);
	intree->SetBranchAddress("j2_tcheBtag", &t->j2_tcheBtag);
	intree->SetBranchAddress("j2_radionMatched", &t->j2_radionMatched);
	intree->SetBranchAddress("j2_secVtxPt", &t->j2_secVtxPt);
	intree->SetBranchAddress("j2_secVtx3dL", &t->j2_secVtx3dL);
	intree->SetBranchAddress("j2_emfrac", &t->j2_emfrac);
	intree->SetBranchAddress("j2_hadfrac", &t->j2_hadfrac);
	intree->SetBranchAddress("j2_btagSF", &t->j2_btagSF);
	intree->SetBranchAddress("j2_ntk", &t->j2_ntk);
	intree->SetBranchAddress("j2_nNeutrals", &t->j2_nNeutrals);
	intree->SetBranchAddress("j2_nCharged", &t->j2_nCharged);
	intree->SetBranchAddress("j2_axis1", &t->j2_axis1);
	intree->SetBranchAddress("j2_axis2", &t->j2_axis2);
	intree->SetBranchAddress("j2_pull", &t->j2_pull);

	intree->SetBranchAddress("j3_e", &t->j3_e);
	intree->SetBranchAddress("j3_pt", &t->j3_pt);
	intree->SetBranchAddress("j3_phi", &t->j3_phi);
	intree->SetBranchAddress("j3_eta", &t->j3_eta);
	intree->SetBranchAddress("j3_beta", &t->j3_beta);
	intree->SetBranchAddress("j3_betaStar", &t->j3_betaStar);
	intree->SetBranchAddress("j3_betaStarClassic", &t->j3_betaStarClassic);
	intree->SetBranchAddress("j3_dR2Mean", &t->j3_dR2Mean);
	intree->SetBranchAddress("j3_csvBtag", &t->j3_csvBtag);
	intree->SetBranchAddress("j3_csvMvaBtag", &t->j3_csvMvaBtag);
	intree->SetBranchAddress("j3_jetProbBtag", &t->j3_jetProbBtag);
	intree->SetBranchAddress("j3_tcheBtag", &t->j3_tcheBtag);
	intree->SetBranchAddress("j3_radionMatched", &t->j3_radionMatched);
	intree->SetBranchAddress("j3_secVtxPt", &t->j3_secVtxPt);
	intree->SetBranchAddress("j3_secVtx3dL", &t->j3_secVtx3dL);
	intree->SetBranchAddress("j3_emfrac", &t->j3_emfrac);
	intree->SetBranchAddress("j3_hadfrac", &t->j3_hadfrac);
	intree->SetBranchAddress("j3_btagSF", &t->j3_btagSF);
	intree->SetBranchAddress("j3_ntk", &t->j3_ntk);
	intree->SetBranchAddress("j3_nNeutrals", &t->j3_nNeutrals);
	intree->SetBranchAddress("j3_nCharged", &t->j3_nCharged);
	intree->SetBranchAddress("j3_axis1", &t->j3_axis1);
	intree->SetBranchAddress("j3_axis2", &t->j3_axis2);
	intree->SetBranchAddress("j3_pull", &t->j3_pull);

	intree->SetBranchAddress("j4_e", &t->j4_e);
	intree->SetBranchAddress("j4_pt", &t->j4_pt);
	intree->SetBranchAddress("j4_phi", &t->j4_phi);
	intree->SetBranchAddress("j4_eta", &t->j4_eta);
	intree->SetBranchAddress("j4_beta", &t->j4_beta);
	intree->SetBranchAddress("j4_betaStar", &t->j4_betaStar);
	intree->SetBranchAddress("j4_betaStarClassic", &t->j4_betaStarClassic);
	intree->SetBranchAddress("j4_dR2Mean", &t->j4_dR2Mean);
	intree->SetBranchAddress("j4_csvBtag", &t->j4_csvBtag);
	intree->SetBranchAddress("j4_csvMvaBtag", &t->j4_csvMvaBtag);
	intree->SetBranchAddress("j4_jetProbBtag", &t->j4_jetProbBtag);
	intree->SetBranchAddress("j4_tcheBtag", &t->j4_tcheBtag);
	intree->SetBranchAddress("j4_radionMatched", &t->j4_radionMatched);
	intree->SetBranchAddress("j4_secVtxPt", &t->j4_secVtxPt);
	intree->SetBranchAddress("j4_secVtx3dL", &t->j4_secVtx3dL);
	intree->SetBranchAddress("j4_emfrac", &t->j4_emfrac);
	intree->SetBranchAddress("j4_hadfrac", &t->j4_hadfrac);
	intree->SetBranchAddress("j4_btagSF", &t->j4_btagSF);
	intree->SetBranchAddress("j4_ntk", &t->j4_ntk);
	intree->SetBranchAddress("j4_nNeutrals", &t->j4_nNeutrals);
	intree->SetBranchAddress("j4_nCharged", &t->j4_nCharged);
	intree->SetBranchAddress("j4_axis1", &t->j4_axis1);
	intree->SetBranchAddress("j4_axis2", &t->j4_axis2);
	intree->SetBranchAddress("j4_pull", &t->j4_pull);

	return;
}

void setup_outtree(TTree* outtree, tree_variables *t)
{
	outtree->Branch("category", &t->category, "category/I");
	outtree->Branch("selection_cut_level", &t->selection_cut_level, "selection_cut_level/I");
	outtree->Branch("event", &t->event, "event/F");
	outtree->Branch("vtx_z", &t->vtx_z, "vtx_z/F");
	outtree->Branch("weight", &t->weight, "weight/F");
	outtree->Branch("evweight", &t->evweight, "evweight/F");
	outtree->Branch("pu_weight", &t->pu_weight, "pu_weight/F");
	outtree->Branch("nvtx", &t->nvtx, "nvtx/F");
	outtree->Branch("rho", &t->rho, "rho/F");
	outtree->Branch("met_corr_pfmet", &t->met_corr_pfmet, "met_corr_pfmet/F");
	outtree->Branch("met_corr_phi_pfmet", &t->met_corr_phi_pfmet, "met_corr_phi_pfmet/F");
	outtree->Branch("met_corr_eta_pfmet", &t->met_corr_eta_pfmet, "met_corr_eta_pfmet/F");
	outtree->Branch("met_corr_e_pfmet", &t->met_corr_e_pfmet, "met_corr_e_pfmet/F");
	outtree->Branch("pho1_pt", &t->pho1_pt, "pho1_pt/F");
	outtree->Branch("pho1_e", &t->pho1_e, "pho1_e/F");
	outtree->Branch("pho1_phi", &t->pho1_phi, "pho1_phi/F");
	outtree->Branch("pho1_eta", &t->pho1_eta, "pho1_eta/F");
	outtree->Branch("pho1_mass", &t->pho1_mass, "pho1_mass/F");
	outtree->Branch("pho1_r9", &t->pho1_r9, "pho1_r9/F");
	outtree->Branch("pho1_sieie", &t->pho1_sieie, "pho1_sieie/F");
	outtree->Branch("pho1_hoe", &t->pho1_hoe, "pho1_hoe/F");
	outtree->Branch("pho1_isEB", &t->pho1_isEB, "pho1_isEB/I");
	outtree->Branch("pho1_pfchargedisogood03", &t->pho1_pfchargedisogood03, "pho1_pfchargedisogood03/F");
	outtree->Branch("pho1_ecaliso", &t->pho1_ecaliso, "pho1_ecaliso/F");
	outtree->Branch("pho1_pfchargedisobad04", &t->pho1_pfchargedisobad04, "pho1_pfchargedisobad04/F");
	outtree->Branch("pho1_ecalisobad", &t->pho1_ecalisobad, "pho1_ecalisobad/F");
	outtree->Branch("pho1_badvtx_Et", &t->pho1_badvtx_Et, "pho1_badvtx_Et/F");
	outtree->Branch("pho1_isconv", &t->pho1_isconv, "pho1_isconv/F");
	outtree->Branch("pho1_PFisoA", &t->pho1_PFisoA, "pho1_PFisoA/F");
	outtree->Branch("pho1_PFisoB", &t->pho1_PFisoB, "pho1_PFisoB/F");
	outtree->Branch("pho1_PFisoC", &t->pho1_PFisoC, "pho1_PFisoC/F");
	outtree->Branch("pho2_pt", &t->pho2_pt, "pho2_pt/F");
	outtree->Branch("pho2_e", &t->pho2_e, "pho2_e/F");
	outtree->Branch("pho2_phi", &t->pho2_phi, "pho2_phi/F");
	outtree->Branch("pho2_eta", &t->pho2_eta, "pho2_eta/F");
	outtree->Branch("pho2_mass", &t->pho2_mass, "pho2_mass/F");
	outtree->Branch("pho2_r9", &t->pho2_r9, "pho2_r9/F");
	outtree->Branch("pho2_sieie", &t->pho2_sieie, "pho2_sieie/F");
	outtree->Branch("pho2_hoe", &t->pho2_hoe, "pho2_hoe/F");
	outtree->Branch("pho2_isEB", &t->pho2_isEB, "pho2_isEB/I");
	outtree->Branch("pho2_pfchargedisogood03", &t->pho2_pfchargedisogood03, "pho2_pfchargedisogood03/F");
	outtree->Branch("pho2_ecaliso", &t->pho2_ecaliso, "pho2_ecaliso/F");
	outtree->Branch("pho2_pfchargedisobad04", &t->pho2_pfchargedisobad04, "pho2_pfchargedisobad04/F");
	outtree->Branch("pho2_ecalisobad", &t->pho2_ecalisobad, "pho2_ecalisobad/F");
	outtree->Branch("pho2_badvtx_Et", &t->pho2_badvtx_Et, "pho2_badvtx_Et/F");
	outtree->Branch("pho2_isconv", &t->pho2_isconv, "pho2_isconv/F");
	outtree->Branch("pho2_PFisoA", &t->pho2_PFisoA, "pho2_PFisoA/F");
	outtree->Branch("pho2_PFisoB", &t->pho2_PFisoB, "pho2_PFisoB/F");
	outtree->Branch("pho2_PFisoC", &t->pho2_PFisoC, "pho2_PFisoC/F");
	outtree->Branch("jet1_pt", &t->jet1_pt, "jet1_pt/F");
	outtree->Branch("jet1_pt", &t->jet1_pt, "jet1_pt/F");
	outtree->Branch("jet1_e", &t->jet1_e, "jet1_e/F");
	outtree->Branch("jet1_phi", &t->jet1_phi, "jet1_phi/F");
	outtree->Branch("jet1_eta", &t->jet1_eta, "jet1_eta/F");
	outtree->Branch("jet1_mass", &t->jet1_mass, "jet1_mass/F");
	outtree->Branch("jet1_csvBtag", &t->jet1_csvBtag, "jet1_csvBtag/F");
	outtree->Branch("jet1_btagSF", &t->jet1_btagSF, "jet1_btagSF/F");
	outtree->Branch("jet1_betaStarClassic", &t->jet1_betaStarClassic, "jet1_betaStarClassic/F");
	outtree->Branch("jet1_dR2Mean", &t->jet1_dR2Mean, "jet1_dR2Mean/F");
	outtree->Branch("jet2_pt", &t->jet2_pt, "jet2_pt/F");
	outtree->Branch("jet2_e", &t->jet2_e, "jet2_e/F");
	outtree->Branch("jet2_phi", &t->jet2_phi, "jet2_phi/F");
	outtree->Branch("jet2_eta", &t->jet2_eta, "jet2_eta/F");
	outtree->Branch("jet2_mass", &t->jet2_mass, "jet2_mass/F");
	outtree->Branch("jet2_csvBtag", &t->jet2_csvBtag, "jet2_csvBtag/F");
	outtree->Branch("jet2_btagSF", &t->jet2_btagSF, "jet2_btagSF/F");
	outtree->Branch("jet2_betaStarClassic", &t->jet2_betaStarClassic, "jet2_betaStarClassic/F");
	outtree->Branch("jet2_dR2Mean", &t->jet2_dR2Mean, "jet2_dR2Mean/F");
// storing inputs of the regression for comparison
	outtree->Branch("regjet1_emfrac", &t->regjet1_emfrac, "regjet1_emfrac/F");
	outtree->Branch("regjet1_hadfrac", &t->regjet1_hadfrac, "regjet1_hadfrac/F");
	outtree->Branch("regjet1_secVtxPt", &t->regjet1_secVtxPt, "regjet1_secVtxPt/F");
	outtree->Branch("regjet1_secVtx3dL", &t->regjet1_secVtx3dL, "regjet1_secVtx3dL/F");
	outtree->Branch("regjet1_dPhiMet", &t->regjet1_dPhiMet, "regjet1_dPhiMet/F");
	outtree->Branch("regjet1_nConstituents", &t->regjet1_nConstituents, "regjet1_nConstituents/I");
	outtree->Branch("regjet2_emfrac", &t->regjet2_emfrac, "regjet2_emfrac/F");
	outtree->Branch("regjet2_hadfrac", &t->regjet2_hadfrac, "regjet2_hadfrac/F");
	outtree->Branch("regjet2_secVtxPt", &t->regjet2_secVtxPt, "regjet2_secVtxPt/F");
	outtree->Branch("regjet2_secVtx3dL", &t->regjet2_secVtx3dL, "regjet2_secVtx3dL/F");
	outtree->Branch("regjet2_dPhiMet", &t->regjet2_dPhiMet, "regjet2_dPhiMet/F");
	outtree->Branch("regjet2_nConstituents", &t->regjet2_nConstituents, "regjet2_nConstituents/I");
// regressed / kin fitted jets
	outtree->Branch("regjet1_pt", &t->regjet1_pt, "regjet1_pt/F");
	outtree->Branch("regjet1_e", &t->regjet1_e, "regjet1_e/F");
	outtree->Branch("regjet1_phi", &t->regjet1_phi, "regjet1_phi/F");
	outtree->Branch("regjet1_eta", &t->regjet1_eta, "regjet1_eta/F");
	outtree->Branch("regjet1_mass", &t->regjet1_mass, "regjet1_mass/F");
	outtree->Branch("regjet1_csvBtag", &t->regjet1_csvBtag, "regjet1_csvBtag/F");
	outtree->Branch("regjet1_btagSF", &t->regjet1_btagSF, "regjet1_btagSF/F");
	outtree->Branch("regjet1_betaStarClassic", &t->regjet1_betaStarClassic, "regjet1_betaStarClassic/F");
	outtree->Branch("regjet1_dR2Mean", &t->regjet1_dR2Mean, "regjet1_dR2Mean/F");
	outtree->Branch("regjet2_pt", &t->regjet2_pt, "regjet2_pt/F");
	outtree->Branch("regjet2_e", &t->regjet2_e, "regjet2_e/F");
	outtree->Branch("regjet2_phi", &t->regjet2_phi, "regjet2_phi/F");
	outtree->Branch("regjet2_eta", &t->regjet2_eta, "regjet2_eta/F");
	outtree->Branch("regjet2_mass", &t->regjet2_mass, "regjet2_mass/F");
	outtree->Branch("regjet2_csvBtag", &t->regjet2_csvBtag, "regjet2_csvBtag/F");
	outtree->Branch("regjet2_btagSF", &t->regjet2_btagSF, "regjet2_btagSF/F");
	outtree->Branch("regjet2_betaStarClassic", &t->regjet2_betaStarClassic, "regjet2_betaStarClassic/F");
	outtree->Branch("regjet2_dR2Mean", &t->regjet2_dR2Mean, "regjet2_dR2Mean/F");
	outtree->Branch("regkinjet1_pt", &t->regkinjet1_pt, "regkinjet1_pt/F");
	outtree->Branch("regkinjet1_e", &t->regkinjet1_e, "regkinjet1_e/F");
	outtree->Branch("regkinjet1_phi", &t->regkinjet1_phi, "regkinjet1_phi/F");
	outtree->Branch("regkinjet1_eta", &t->regkinjet1_eta, "regkinjet1_eta/F");
	outtree->Branch("regkinjet1_mass", &t->regkinjet1_mass, "regkinjet1_mass/F");
	outtree->Branch("regkinjet1_csvBtag", &t->regkinjet1_csvBtag, "regkinjet1_csvBtag/F");
	outtree->Branch("regkinjet1_btagSF", &t->regkinjet1_btagSF, "regkinjet1_btagSF/F");
	outtree->Branch("regkinjet1_betaStarClassic", &t->regkinjet1_betaStarClassic, "regkinjet1_betaStarClassic/F");
	outtree->Branch("regkinjet1_dR2Mean", &t->regkinjet1_dR2Mean, "regkinjet1_dR2Mean/F");
	outtree->Branch("regkinjet2_pt", &t->regkinjet2_pt, "regkinjet2_pt/F");
	outtree->Branch("regkinjet2_e", &t->regkinjet2_e, "regkinjet2_e/F");
	outtree->Branch("regkinjet2_phi", &t->regkinjet2_phi, "regkinjet2_phi/F");
	outtree->Branch("regkinjet2_eta", &t->regkinjet2_eta, "regkinjet2_eta/F");
	outtree->Branch("regkinjet2_mass", &t->regkinjet2_mass, "regkinjet2_mass/F");
	outtree->Branch("regkinjet2_csvBtag", &t->regkinjet2_csvBtag, "regkinjet2_csvBtag/F");
	outtree->Branch("regkinjet2_btagSF", &t->regkinjet2_btagSF, "regkinjet2_btagSF/F");
	outtree->Branch("regkinjet2_betaStarClassic", &t->regkinjet2_betaStarClassic, "regkinjet2_betaStarClassic/F");
	outtree->Branch("regkinjet2_dR2Mean", &t->regkinjet2_dR2Mean, "regkinjet2_dR2Mean/F");
	outtree->Branch("kinjet1_pt", &t->kinjet1_pt, "kinjet1_pt/F");
	outtree->Branch("kinjet1_e", &t->kinjet1_e, "kinjet1_e/F");
	outtree->Branch("kinjet1_phi", &t->kinjet1_phi, "kinjet1_phi/F");
	outtree->Branch("kinjet1_eta", &t->kinjet1_eta, "kinjet1_eta/F");
	outtree->Branch("kinjet1_mass", &t->kinjet1_mass, "kinjet1_mass/F");
	outtree->Branch("kinjet1_csvBtag", &t->kinjet1_csvBtag, "kinjet1_csvBtag/F");
	outtree->Branch("kinjet1_btagSF", &t->kinjet1_btagSF, "kinjet1_btagSF/F");
	outtree->Branch("kinjet1_betaStarClassic", &t->kinjet1_betaStarClassic, "kinjet1_betaStarClassic/F");
	outtree->Branch("kinjet1_dR2Mean", &t->kinjet1_dR2Mean, "kinjet1_dR2Mean/F");
	outtree->Branch("kinjet2_pt", &t->kinjet2_pt, "kinjet2_pt/F");
	outtree->Branch("kinjet2_e", &t->kinjet2_e, "kinjet2_e/F");
	outtree->Branch("kinjet2_phi", &t->kinjet2_phi, "kinjet2_phi/F");
	outtree->Branch("kinjet2_eta", &t->kinjet2_eta, "kinjet2_eta/F");
	outtree->Branch("kinjet2_mass", &t->kinjet2_mass, "kinjet2_mass/F");
	outtree->Branch("kinjet2_csvBtag", &t->kinjet2_csvBtag, "kinjet2_csvBtag/F");
	outtree->Branch("kinjet2_btagSF", &t->kinjet2_btagSF, "kinjet2_btagSF/F");
	outtree->Branch("kinjet2_betaStarClassic", &t->kinjet2_betaStarClassic, "kinjet2_betaStarClassic/F");
	outtree->Branch("kinjet2_dR2Mean", &t->kinjet2_dR2Mean, "kinjet2_dR2Mean/F");
	outtree->Branch("jj_pt", &t->jj_pt, "jj_pt/F");
	outtree->Branch("jj_e", &t->jj_e, "jj_e/F");
	outtree->Branch("jj_phi", &t->jj_phi, "jj_phi/F");
	outtree->Branch("jj_eta", &t->jj_eta, "jj_eta/F");
	outtree->Branch("jj_mass", &t->jj_mass, "jj_mass/F");
	outtree->Branch("jj_btagSF", &t->jj_btagSF, "jj_btagSF/F");
	outtree->Branch("jj_DR", &t->jj_DR, "jj_DR/F");
	outtree->Branch("regjj_pt", &t->regjj_pt, "regjj_pt/F");
	outtree->Branch("regjj_e", &t->regjj_e, "regjj_e/F");
	outtree->Branch("regjj_phi", &t->regjj_phi, "regjj_phi/F");
	outtree->Branch("regjj_eta", &t->regjj_eta, "regjj_eta/F");
	outtree->Branch("regjj_mass", &t->regjj_mass, "regjj_mass/F");
	outtree->Branch("regjj_btagSF", &t->regjj_btagSF, "regjj_btagSF/F");
	outtree->Branch("regjj_DR", &t->regjj_DR, "regjj_DR/F");
	outtree->Branch("regkinjj_pt", &t->regkinjj_pt, "regkinjj_pt/F");
	outtree->Branch("regkinjj_e", &t->regkinjj_e, "regkinjj_e/F");
	outtree->Branch("regkinjj_phi", &t->regkinjj_phi, "regkinjj_phi/F");
	outtree->Branch("regkinjj_eta", &t->regkinjj_eta, "regkinjj_eta/F");
	outtree->Branch("regkinjj_mass", &t->regkinjj_mass, "regkinjj_mass/F");
	outtree->Branch("regkinjj_btagSF", &t->regkinjj_btagSF, "regkinjj_btagSF/F");
	outtree->Branch("regkinjj_DR", &t->regkinjj_DR, "regkinjj_DR/F");
	outtree->Branch("kinjj_pt", &t->kinjj_pt, "kinjj_pt/F");
	outtree->Branch("kinjj_e", &t->kinjj_e, "kinjj_e/F");
	outtree->Branch("kinjj_phi", &t->kinjj_phi, "kinjj_phi/F");
	outtree->Branch("kinjj_eta", &t->kinjj_eta, "kinjj_eta/F");
	outtree->Branch("kinjj_mass", &t->kinjj_mass, "kinjj_mass/F");
	outtree->Branch("kinjj_btagSF", &t->kinjj_btagSF, "kinjj_btagSF/F");
	outtree->Branch("kinjj_DR", &t->kinjj_DR, "kinjj_DR/F");
	outtree->Branch("gg_pt", &t->gg_pt, "gg_pt/F");
	outtree->Branch("gg_e", &t->gg_e, "gg_e/F");
	outtree->Branch("gg_phi", &t->gg_phi, "gg_phi/F");
	outtree->Branch("gg_eta", &t->gg_eta, "gg_eta/F");
	outtree->Branch("gg_mass", &t->gg_mass, "gg_mass/F");
	outtree->Branch("ggjj_pt", &t->ggjj_pt, "ggjj_pt/F");
	outtree->Branch("ggjj_e", &t->ggjj_e, "ggjj_e/F");
	outtree->Branch("ggjj_phi", &t->ggjj_phi, "ggjj_phi/F");
	outtree->Branch("ggjj_eta", &t->ggjj_eta, "ggjj_eta/F");
	outtree->Branch("ggjj_mass", &t->ggjj_mass, "ggjj_mass/F");
	outtree->Branch("regggjj_pt", &t->regggjj_pt, "regggjj_pt/F");
	outtree->Branch("regggjj_e", &t->regggjj_e, "regggjj_e/F");
	outtree->Branch("regggjj_phi", &t->regggjj_phi, "regggjj_phi/F");
	outtree->Branch("regggjj_eta", &t->regggjj_eta, "regggjj_eta/F");
	outtree->Branch("regggjj_mass", &t->regggjj_mass, "regggjj_mass/F");
	outtree->Branch("regkinggjj_pt", &t->regkinggjj_pt, "regkinggjj_pt/F");
	outtree->Branch("regkinggjj_e", &t->regkinggjj_e, "regkinggjj_e/F");
	outtree->Branch("regkinggjj_phi", &t->regkinggjj_phi, "regkinggjj_phi/F");
	outtree->Branch("regkinggjj_eta", &t->regkinggjj_eta, "regkinggjj_eta/F");
	outtree->Branch("regkinggjj_mass", &t->regkinggjj_mass, "regkinggjj_mass/F");
	outtree->Branch("kinggjj_pt", &t->kinggjj_pt, "kinggjj_pt/F");
	outtree->Branch("kinggjj_e", &t->kinggjj_e, "kinggjj_e/F");
	outtree->Branch("kinggjj_phi", &t->kinggjj_phi, "kinggjj_phi/F");
	outtree->Branch("kinggjj_eta", &t->kinggjj_eta, "kinggjj_eta/F");
	outtree->Branch("kinggjj_mass", &t->kinggjj_mass, "kinggjj_mass/F");
	outtree->Branch("njets_kLooseID", &t->njets_kLooseID, "njets_kLooseID/I");
	outtree->Branch("njets_kLooseID_and_CSVM", &t->njets_kLooseID_and_CSVM, "njets_kLooseID_and_CSVM/I");
	outtree->Branch("njets_kRadionID", &t->njets_kRadionID, "njets_kRadionID/I");
	outtree->Branch("njets_kRadionID_and_CSVM", &t->njets_kRadionID_and_CSVM, "njets_kRadionID_and_CSVM/I");
	outtree->Branch("costhetastar", &t->costhetastar, "costhetastar/F");
	outtree->Branch("regcosthetastar", &t->regcosthetastar, "regcosthetastar/F");
	outtree->Branch("regkincosthetastar", &t->regkincosthetastar, "regkincosthetastar/F");
	outtree->Branch("kincosthetastar", &t->kincosthetastar, "kincosthetastar/F");
	outtree->Branch("minDRgj", &t->minDRgj, "minDRgj/F");
	outtree->Branch("minDRgregj", &t->minDRgregj, "minDRgregj/F");
	outtree->Branch("minDRgregkinj", &t->minDRgregkinj, "minDRgregkinj/F");
	outtree->Branch("minDRgkinj", &t->minDRgkinj, "minDRgkinj/F");
	outtree->Branch("HT_gg", &t->HT_gg, "HT_gg/F");
// gen level info
	outtree->Branch("gr_radion_p4_pt", &t->gr_radion_p4_pt, "gr_radion_p4_pt/F");
	outtree->Branch("gr_radion_p4_eta", &t->gr_radion_p4_eta, "gr_radion_p4_eta/F");
	outtree->Branch("gr_radion_p4_phi", &t->gr_radion_p4_phi, "gr_radion_p4_phi/F");
	outtree->Branch("gr_radion_p4_mass", &t->gr_radion_p4_mass, "gr_radion_p4_mass/F");
	outtree->Branch("gr_hgg_p4_pt", &t->gr_hgg_p4_pt, "gr_hgg_p4_pt/F");
	outtree->Branch("gr_hgg_p4_eta", &t->gr_hgg_p4_eta, "gr_hgg_p4_eta/F");
	outtree->Branch("gr_hgg_p4_phi", &t->gr_hgg_p4_phi, "gr_hgg_p4_phi/F");
	outtree->Branch("gr_hgg_p4_mass", &t->gr_hgg_p4_mass, "gr_hgg_p4_mass/F");
	outtree->Branch("gr_hbb_p4_pt", &t->gr_hbb_p4_pt, "gr_hbb_p4_pt/F");
	outtree->Branch("gr_hbb_p4_eta", &t->gr_hbb_p4_eta, "gr_hbb_p4_eta/F");
	outtree->Branch("gr_hbb_p4_phi", &t->gr_hbb_p4_phi, "gr_hbb_p4_phi/F");
	outtree->Branch("gr_hbb_p4_mass", &t->gr_hbb_p4_mass, "gr_hbb_p4_mass/F");
	outtree->Branch("gr_hjj_p4_pt", &t->gr_hjj_p4_pt, "gr_hjj_p4_pt/F");
	outtree->Branch("gr_hjj_p4_eta", &t->gr_hjj_p4_eta, "gr_hjj_p4_eta/F");
	outtree->Branch("gr_hjj_p4_phi", &t->gr_hjj_p4_phi, "gr_hjj_p4_phi/F");
	outtree->Branch("gr_hjj_p4_mass", &t->gr_hjj_p4_mass, "gr_hjj_p4_mass/F");
	outtree->Branch("gr_g1_p4_pt", &t->gr_g1_p4_pt, "gr_g1_p4_pt/F");
	outtree->Branch("gr_g1_p4_eta", &t->gr_g1_p4_eta, "gr_g1_p4_eta/F");
	outtree->Branch("gr_g1_p4_phi", &t->gr_g1_p4_phi, "gr_g1_p4_phi/F");
	outtree->Branch("gr_g1_p4_mass", &t->gr_g1_p4_mass, "gr_g1_p4_mass/F");
	outtree->Branch("gr_g2_p4_pt", &t->gr_g2_p4_pt, "gr_g2_p4_pt/F");
	outtree->Branch("gr_g2_p4_eta", &t->gr_g2_p4_eta, "gr_g2_p4_eta/F");
	outtree->Branch("gr_g2_p4_phi", &t->gr_g2_p4_phi, "gr_g2_p4_phi/F");
	outtree->Branch("gr_g2_p4_mass", &t->gr_g2_p4_mass, "gr_g2_p4_mass/F");
	outtree->Branch("gr_b1_p4_pt", &t->gr_b1_p4_pt, "gr_b1_p4_pt/F");
	outtree->Branch("gr_b1_p4_eta", &t->gr_b1_p4_eta, "gr_b1_p4_eta/F");
	outtree->Branch("gr_b1_p4_phi", &t->gr_b1_p4_phi, "gr_b1_p4_phi/F");
	outtree->Branch("gr_b1_p4_mass", &t->gr_b1_p4_mass, "gr_b1_p4_mass/F");
	outtree->Branch("gr_b2_p4_pt", &t->gr_b2_p4_pt, "gr_b2_p4_pt/F");
	outtree->Branch("gr_b2_p4_eta", &t->gr_b2_p4_eta, "gr_b2_p4_eta/F");
	outtree->Branch("gr_b2_p4_phi", &t->gr_b2_p4_phi, "gr_b2_p4_phi/F");
	outtree->Branch("gr_b2_p4_mass", &t->gr_b2_p4_mass, "gr_b2_p4_mass/F");
	outtree->Branch("gr_j1_p4_pt", &t->gr_j1_p4_pt, "gr_j1_p4_pt/F");
	outtree->Branch("gr_j1_p4_eta", &t->gr_j1_p4_eta, "gr_j1_p4_eta/F");
	outtree->Branch("gr_j1_p4_phi", &t->gr_j1_p4_phi, "gr_j1_p4_phi/F");
	outtree->Branch("gr_j1_p4_mass", &t->gr_j1_p4_mass, "gr_j1_p4_mass/F");
	outtree->Branch("gr_j2_p4_pt", &t->gr_j2_p4_pt, "gr_j2_p4_pt/F");
	outtree->Branch("gr_j2_p4_eta", &t->gr_j2_p4_eta, "gr_j2_p4_eta/F");
	outtree->Branch("gr_j2_p4_phi", &t->gr_j2_p4_phi, "gr_j2_p4_phi/F");
	outtree->Branch("gr_j2_p4_mass", &t->gr_j2_p4_mass, "gr_j2_p4_mass/F");

	return;
}


